name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 Push될 때 실행

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 Clone
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH로 EC2 서버에 연결하고 배포 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 9022
          script: |
            # 작업 디렉토리로 이동
            cd /home/ec2-user/site-wiki-be

            # Git 최신 코드 가져오기
            git pull origin main

            # Yarn 설치 및 의존성 설치
            npm install

            # 기존 실행 중인 앱 중지
            pm2 stop all || true

            # PM2로 앱 실행
            pm2 start ./ecosystem.config.js

            # PM2 실행 상태 확인
            pm2 status
